# Generated by Django 5.1.7 on 2025-03-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_alter_trainee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='age',
        ),
        migrations.AddField(
            model_name='trainee',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
